### PR TITLE
Sync tests start stop with custom path and test algorithm

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#1887

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/97)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/97)* status: all files reviewed, 12 unresolved discussions (waiting on @RonShvarz)

___
*[`pipelines/temp.json` line 1 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnOw8r4wggUb8lRXid:-NrnOw8r4wggUb8lRXie:b-28cljj) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1336ed5cd46c4742c22cbc27fad2161995bb6312/pipelines/temp.json#L1)):*
> ```JSON
> {"name":"r3crnm3v","nodes":[{"nodeName":"green","algorithmName":"green-alg","input":["@flowInput.files.link"]},{"nodeName":"yellow","algorithmName":"yellow-alg","input":["@green"]},{"nodeName":"black","algorithmName":"black-alg","input":["@yellow"]}],"flowInput":{"files":{"link":"links-1"}},"options":{"batchTolerance":100,"progressVerbosityLevel":"debug","ttl":3600},"experimentName":"main","priority":3}
> ```

Looks like a temp file that shouldn't be commited



_Code quote:_
```JSON
{"name":"r3crnm3v","nodes":[{"nodeName":"green","algorithmName":"green-alg","input":["@flowInput.files.link"]},{"nodeName":"yellow","algorithmName":"yellow-alg","input":["@green"]},{"nodeName":"black","algorithmName":"black-alg","input":["@yellow"]}],"flowInput":{"files":{"link":"links-1"}},"options":{"batchTolerance":100,"progressVerbosityLevel":"debug","ttl":3600},"experimentName":"main","priority":3}
```
___
*[`tests/cliTests.js` line 591 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnP_Iu3g6Pm5hVbq0i:-NrnP_Iu3g6Pm5hVbq0j:bg888md) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L591)):*
> ```JavaScript
>                     pending: false
>                 }
>             }
> ```

Try to delete somealg algorithm first to make sure we start fresh.
___
*[`tests/cliTests.js` line 612 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnQWVUA45UQU0L5g1s:-NrnQWVUA45UQU0L5g1t:b1hcfdd) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L612)):*
> ```JavaScript
>         }).timeout(1000 * 60 * 10)
> 
>         it('sync stop algorithm should have devMode = false, and no devFolder', async () => {
> ```

Delete the algorithm then create it with the devMode true then check if stop works
___
*[`tests/cliTests.js` line 642 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnTpjq4pbKmE7QNIiZ:-NrnTpjq4pbKmE7QNIi_:b9uoakv) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L642)):*
> ```JavaScript
> 
>             expect(devFolder).to.be.equal(null);
>             expect(devMode).to.be.equal(false);
> ```

delete the algorithm at the end
___
*[`tests/cliTests.js` line 645 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnQmPY2T5nY9VldIaw:-NrnQmPY2T5nY9VldIax:b-4b488e) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L645)):*
> ```JavaScript
>         }).timeout(1000 * 60 * 10)
> 
>         it.only('sync an algorithm with a custom path using start,stop, and a devFolder', async () => {
> ```

Remove the only



_Code quote:_
```JavaScript
only
```
___
*[`tests/cliTests.js` line 646 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnTyni1N6ye08S5xt5:-NrnTyni1N6ye08S5xt6:b-lkxef9) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L646)):*
> ```JavaScript
> 
>         it.only('sync an algorithm with a custom path using start,stop, and a devFolder', async () => {
>             const randomName = pipelineRandomName(8).toLowerCase()
> ```

delete randomeName algorithm at the end.
___
*[`tests/cliTests.js` line 668 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnRfcV6az69HEH3bhU:-NrnRfcV6az69HEH3bhV:bxbewbr) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L668)):*
> ```JavaScript
>               await exceSyncString(startCommand)
>            
>               await delay(10 * 1000)
> ```

No need for this sleep, change occures immediatly



_Code quote:_
```JavaScript
 await delay(10 * 1000)
```
___
*[`tests/cliTests.js` line 671 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnS1pI39cwjjVDq58E:-NrnS1pJ2j6xpgcqS4Tp:b30vs4p) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L671)):*
> ```JavaScript
> 
>             // // sync watch
>             const res = await runStored(devPipeline);
> ```

Run stroed should happen after watch command invoked and delay time passed.



_Code quote:_
```JavaScript
   const res = await runStored(devPipeline);
```
___
*[`tests/cliTests.js` line 694 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnSUk_7iD-YR4BavTa:-NrnSUk_7iD-YR4BavTb:b-4yqeg2) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L694)):*
> ```JavaScript
> 
>             expect(devFolder).to.be.equal(null);
>             expect(devMode).to.be.equal(false);
> ```

Stop has already been tested



_Code quote:_
```JavaScript
            const stopCommand = ` hkubectl sync stop` +
                ` --algorithmName ${algName}`

            console.log(stopCommand)
            await exceSyncString(stopCommand)

            await delay(10 * 1000)

            const alg = await getAlgorithm(algName)
            const  { devMode, devFolder } = alg.body.options

            expect(devFolder).to.be.equal(null);
            expect(devMode).to.be.equal(false);
```
___
*[`tests/cliTests.js` line 697 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnUB6J7_b0q1QpgeZV:-NrnUB6K2FsPASNaAKO-:b8hl0rg) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L697)):*
> ```JavaScript
>         }).timeout(1000 * 60 * 10)
> 
>         it.only('algorithm should fail finding a synced file', async () => {
> ```

Remove the only.



_Code quote:_
```JavaScript
only
```
___
*[`tests/cliTests.js` line 726 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnVJjQByGPboBTfSho:-NrnVJjQByGPboBTfShp:bxqenwz) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L726)):*
> ```JavaScript
>             // get status
>             const pipelineData = await getPipelineStatus(res.body.jobId);
>             expect(pipelineData.body.status).be.equal('failed');
> ```

You can remove this test and run this check before you start wach in the previouse test



_Code quote:_
```JavaScript
            expect(pipelineData.body.status).be.equal('failed');
```
___
*[`tests/cliTests.js` line 740 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnUSKWALBAK0isdzCq:-NrnUSKWALBAK0isdzCr:b84w7ta) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L740)):*
> ```JavaScript
>             await deletePipeline(devPipeline);
>             expect(devFolder).to.be.equal(null);
>             expect(devMode).to.be.equal(false);
> ```

stop has been tested twice



_Code quote:_
```JavaScript
            const stopCommand = ` hkubectl sync stop` +
                ` --algorithmName ${algName}`

            console.log(stopCommand)
            await exceSyncString(stopCommand)

            await delay(10 * 1000)

            const alg = await getAlgorithm(algName)
            const  { devMode, devFolder } = alg.body.options
            await deletePipeline(devPipeline);
            expect(devFolder).to.be.equal(null);
            expect(devMode).to.be.equal(false);
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/97)* status: all files reviewed, 12 unresolved discussions (waiting on @golanha)

___
*[`pipelines/temp.json` line 1 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnOw8r4wggUb8lRXid:-NrnWAvJArl52HCbOPKz:bt95zrh) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1336ed5cd46c4742c22cbc27fad2161995bb6312/pipelines/temp.json#L1)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Looks like a temp file that shouldn't be commited
</blockquote></details>

Was indicated to only been modified, hence he was commited in the past.
I can remove it if you wish.
___
*[`tests/cliTests.js` line 591 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnP_Iu3g6Pm5hVbq0i:-NrnWV6t2S3TwaD5WsS1:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L591)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Try to delete somealg algorithm first to make sure we start fresh.
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 612 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnQWVUA45UQU0L5g1s:-NrnWfbQCNN5azJSGqgk:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L612)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Delete the algorithm then create it with the devMode true then check if stop works
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 642 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnTpjq4pbKmE7QNIiZ:-NrnWtWa4njCArW7pgTg:b-y7z9m3) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L642)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

delete the algorithm at the end
</blockquote></details>

algList.push does exactly that
___
*[`tests/cliTests.js` line 645 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnQmPY2T5nY9VldIaw:-NrnWm2Q46VFfTHAKRwr:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L645)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Remove the only
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 646 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnTyni1N6ye08S5xt5:-NrnWoev2enKK1izT7eH:b-y7z9m3) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L646)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

delete randomeName algorithm at the end.
</blockquote></details>

algList.push does exactly that
___
*[`tests/cliTests.js` line 668 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnRfcV6az69HEH3bhU:-NrnX3iBBwAKpXQE6o6B:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L668)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

No need for this sleep, change occures immediatly
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 671 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnS1pI39cwjjVDq58E:-NrnXBU1ASZ2kRXAf88f:bggxrdk) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L671)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Run stroed should happen after watch command invoked and delay time passed.
</blockquote></details>

Changed places, but i leave the delay on for the sake of giving time to the algorithm's creation+internal 25 second sleep to find the file
___
*[`tests/cliTests.js` line 694 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnSUk_7iD-YR4BavTa:-NrnX_p5DXfXSYzrC-b_:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L694)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Stop has already been tested
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 697 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnUB6J7_b0q1QpgeZV:-NrnX_OY2Eu9r3bPS18e:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L697)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Remove the only.
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 726 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnVJjQByGPboBTfSho:-NrnXsTu7kEVM_Jm0Ka4:b-keh69o) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L726)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

You can remove this test and run this check before you start wach in the previouse test
</blockquote></details>

Haivng a seperate test is more to the SOLID principles, lets the other test continue verifying the regression on "watch passing", even if we broke the "watch failing "part
___
*[`tests/cliTests.js` line 740 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnUSKWALBAK0isdzCq:-NrnXg7a1bdsf5c1urBG:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L740)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

stop has been tested twice
</blockquote></details>

Done.

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/97)* status: all files reviewed, 2 unresolved discussions (waiting on @RonShvarz)

___
*[`pipelines/temp.json` line 1 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnOw8r4wggUb8lRXid:-NrnjMr-BcI4AA7WGy5F:bxs8q06) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1336ed5cd46c4742c22cbc27fad2161995bb6312/pipelines/temp.json#L1)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

Was indicated to only been modified, hence he was commited in the past.
I can remove it if you wish.
</blockquote></details>

Yes try to remove
___
*[`tests/cliTests.js` line 726 at r2](https://reviewable.io/reviews/kube-HPC/system-test-node/97#-NrnVJjQByGPboBTfSho:-NrnkvjSCVxLJSlr2Kjb:b-nwcram) ([raw file](https://github.com/kube-HPC/system-test-node/blob/361922e28c8d9ac063cbecb430ad4f6c85ddc13f/tests/cliTests.js#L726)):*
<details><summary><i>Previously, RonShvarz (Ron Shvarzburd) wrote…</i></summary><blockquote>

Haivng a seperate test is more to the SOLID principles, lets the other test continue verifying the regression on "watch passing", even if we broke the "watch failing "part
</blockquote></details>

But this test alone doesn't really check anything.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/97)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
