### PR TITLE
Pods and jobs e2e tests

### PR DESCRIPTION
**Pull request by RonShvarz**
kube-HPC/hkube#1860

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/101)

### CODE REVIEW

**Comment by RonShvarz** [comment]
kube-HPC/hkube#1892

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/101)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @RonShvarz)

___
*[`additionalFiles/defaults/algorithms/stayup.js` line 1 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurYIKa-DmSZb2-STcn:-NurYIKa-DmSZb2-STco:b-nekg68) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/additionalFiles/defaults/algorithms/stayup.js#L1)):*
> ```JavaScript
> const stayUpTest = {
> ```

Rename to stayUpAlg



_Code quote:_
```JavaScript
stayUpTest
```
___
*[`tests/algorithm_test.js` line 1059 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurYNWE-dEEXlCK07PM:-NurYNWE-dEEXlCK07PN:b-p9aawt) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/tests/algorithm_test.js#L1059)):*
> ```JavaScript
>             const stayupAlgName = "stayuptest";
>             const statelessAlgName = "yellow-alg"
>             let stayUpBody = {
> ```

Rename to stayUpAlgThin/ stayUpAlgSkeleton/ stayUpSlim/ stayUpRunAlg



_Code quote:_
```JavaScript
stayUpBody
```
___
*[`tests/algorithm_test.js` line 1097 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurXFns88QQmduKMNHV:-NurXFns88QQmduKMNHW:b-ypz0h3) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/tests/algorithm_test.js#L1097)):*
> ```JavaScript
>                 expect(response.statusCode).to.be.equal(200);
>                 expect(response.body.message.length).to.be.greaterThan(2);
>                 await deleteAlgorithmJobs(stayUpBody.name);
> ```

why do you need to delete the statefull jobs?



_Code quote:_
```JavaScript
await deleteAlgorithmJobs(stayUpBody.name);
```

**Review by golanha — COMMENTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/101)* status: all files reviewed, 3 unresolved discussions (waiting on @RonShvarz)

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/101)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[`additionalFiles/defaults/algorithms/stayup.js` line 1 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurYIKa-DmSZb2-STcn:-NusQy3e1o51s0jXzuFb:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/additionalFiles/defaults/algorithms/stayup.js#L1)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Rename to stayUpAlg
</blockquote></details>

Done.
___
*[`tests/algorithm_test.js` line 1059 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurYNWE-dEEXlCK07PM:-NusQytU1bthPq8BDkQO:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/tests/algorithm_test.js#L1059)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Rename to stayUpAlgThin/ stayUpAlgSkeleton/ stayUpSlim/ stayUpRunAlg
</blockquote></details>

Done.
___
*[`tests/algorithm_test.js` line 1097 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/101#-NurXFns88QQmduKMNHV:-NusQzoGBf7yqSY_tgtN:b-96w417) ([raw file](https://github.com/kube-HPC/system-test-node/blob/1e998b866dfa8ae87d471975a0b7e3eaf47fac94/tests/algorithm_test.js#L1097)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

why do you need to delete the statefull jobs?
</blockquote></details>

After deleting pods, the pods restart due to jobs being present. In order for the following test to run as intended, i use the delete jobs to "reset" the amount of algorithms that are up.

**Review by golanha — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/101)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
