### PR TITLE
hkubectl data migration (export) tests

### PR DESCRIPTION
**Pull request by mkkCoder**
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/89)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/89)* status: all files reviewed, 1 unresolved discussion (waiting on @mkkCoder)

___
*[`tests/cliTests.js` line 568 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-NoqUKs7-mpst5_b2Mn_:-NoqUKs7-mpst5_b2Mna:bdf3773) ([raw file](https://github.com/kube-HPC/system-test-node/blob/11cfa50b1a71557a851af4a2ab9196e0871ec2bf/tests/cliTests.js#L568)):*
> ```JavaScript
>             const rimraf = require('rimraf');
> 
>             const filePath = './additionalFiles/exportedAlgorithms';
> ```

folderpath
Same change in all tests



_Code quote:_
```JavaScript
filePath
```

**Review by golanha — CHANGES_REQUESTED** [review]
You need to create folder .../additionalFiles/exportedAlgorithms 
And folder ./additionalFiles/exportedPipelines 
Before running the test

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-:-NouMZ8d0wHaot7WvQg-:b-zcvf58)* status: all files reviewed, 2 unresolved discussions (waiting on @mkkCoder)

___
*[`tests/cliTests.js` line 591 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-NouMTm53LvvGqpwvLc1:-NouMTm53LvvGqpwvLc2:by4o73i) ([raw file](https://github.com/kube-HPC/system-test-node/blob/11cfa50b1a71557a851af4a2ab9196e0871ec2bf/tests/cliTests.js#L591)):*
> ```JavaScript
>             fs.mkdirSync(filePath); 
>         }).timeout(1000 * 60 * 6)
>     }).timeout(1000 * 60 * 10)
> ```

This closes the describe after one test



_Code quote:_
```JavaScript
    }).timeout(1000 * 60 * 10)
```

**Review by mkkCoder — COMMENTED** [review]
added a check if exists before each test, if not, created it

> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-:-NouZ3QzCV6PLGk-Ykbu:bjmegko)* status: all files reviewed, 2 unresolved discussions (waiting on @golanha)

___
*[`tests/cliTests.js` line 568 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-NoqUKs7-mpst5_b2Mn_:-NouT3g8ArIstGoyCb6K:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/11cfa50b1a71557a851af4a2ab9196e0871ec2bf/tests/cliTests.js#L568)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

folderpath
Same change in all tests
</blockquote></details>

Done.
___
*[`tests/cliTests.js` line 591 at r1](https://reviewable.io/reviews/kube-HPC/system-test-node/89#-NouMTm53LvvGqpwvLc1:-NouZ2-m2_qJASluoLsA:b-896fix) ([raw file](https://github.com/kube-HPC/system-test-node/blob/11cfa50b1a71557a851af4a2ab9196e0871ec2bf/tests/cliTests.js#L591)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

This closes the describe after one test
</blockquote></details>

Done.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/system-test-node/89)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mkkCoder)

**Pull request merged**
